### ISSUE TITLE
Not working with scss variable in production

### ISSUE THREAD

**Issue by SuperDJ** [postcss/postcss-color-hex-alpha#9]
While using postcss-preset-env I get the following results:

    color: #{$black}de;

In development it will return the expected:

    color: rgba(0, 0, 0, 0.87059);

But in production:

    color: #000de;

In `package.json` I have the following scripts:

    "dev": "cross-env webpack-dev-server --config webpack.config.js --mode=development -w --hot",
    "prod": "cross-env webpack --config webpack.config.js --mode=production -p"

And in `webpack.config.js`

    {
		test: /\.(sa|sc|c)ss$/,
		exclude: ['/node_modules', './dist', '/src/js', '/docs'],
		use: [
			MiniCSSExtractPlugin.loader,
			{
				loader: 'css-loader',
				options: {
					sourceMap: true,
					minimize: process.env.NODE_ENV === 'production',
				}
			},
			{
				loader: 'postcss-loader',
				options: {
					sourceMap: true,
					syntax: postCssScss,
					plugins: () => [
						autoprefixer,
						postCssPresetEnv({
							stage: 0,
							features: {
								'color-mod-function': true,
								'alpha-hex-colors': true
							}
						}),
					],
				},
			},
			{
			loader: 'sass-loader',
				options: {
					sourceMap: true
				}
			}
		]
	}

I have tried to use it without the `features` part that didn't work. Also tried to require the `color-mod-function` and `alpha-hex-colors` as seperate package after the `autoprefixer` which also didn't work.

So how can I get the same output from development in production?

**Comment by jonathantneal** [comment]
If you can spin up a small github project that replicates this, I will look into it. Otherwise, I don’t understand if the interplay of these technologies is the issue or what.

**Comment by SuperDJ** [comment]
I have created the following [project](https://github.com/SuperDJ/hex-alpha). I was only able to reproduce the error of an invalid hex value. 

The project that the error originates from is [this](https://github.com/SuperDJ/material). When you take a look at the `.data-table td` you should be able to see what I mean. `src/sass/components/_data-table.scss r19`, `docs/dist/css/material-light.css` and `<localhost_url>/components/data-table.html`

**Comment by jonathantneal** [comment]
Ah! Thanks for posting the project. Unfortunately, the issue is that you are creating a 5 digit hex, as `$` variables are string based.


`#000` + `99` = `#00099`.

**Comment by SuperDJ** [comment]
Maybe it is true for that example project. However in the other project I linked I use the color `#000000` that with `99` should make a valid color however only in development I get an RGBA value not in production.
